"""

    Here we collect the class names of each class set

"""

city19 = ["road",
          "sidewalk",
          "building",
          "wall",
          "fence",
          "pole",
          "traffic light",
          "traffic sign",
          "vegetation",
          "terrain",
          "sky",
          "person",
          "rider",
          "car",
          "truck",
          "bus",
          "train",
          "motorbike",
          "bycicle"]

idd17 = ["road",
         "sidewalk",
         "building",
         "wall",
         "fence",
         "pole",
         "traffic light",
         "traffic sign",
         "vegetation",
         "sky",
         "person",
         "rider",
         "car",
         "truck",
         "bus",
         "motorbike",
         "bycicle"]


synthia16 = ["road",
             "sidewalk",
             "building",
             "wall",
             "fence",
             "pole",
             "traffic light",
             "traffic sign",
             "vegetation",
             "sky",
             "person",
             "rider",
             "car",
             "bus",
             "motorbike",
             "bycicle"]


idda16 = ["road",
          "sidewalk",
          "building",
          "wall",
          "fence",
          "pole",
          "traffic light",
          "traffic sign",
          "vegetation",
          "terrain",
          "sky",
          "person",
          "rider",
          "car",
          "motorbike",
          "bycicle"]


sii15 = ["road",
         "sidewalk",
         "building",
         "wall",
         "fence",
         "pole",
         "traffic light",
         "traffic sign",
         "vegetation",
         "sky",
         "person",
         "rider",
         "car",
         "motorbike",
         "bycicle"]


crosscity13 = ["road",
               "sidewalk",
               "building",
               "traffic light",
               "traffic sign",
               "vegetation",
               "sky",
               "person",
               "rider",
               "car",
               "bus",
               "motorbike",
               "bycicle"]


cci12 = ["road",
       "sidewalk",
       "building",
       "traffic light",
       "traffic sign",
       "vegetation",
       "sky",
       "person",
       "rider",
       "car",
       "motorbike",
       "bycicle"]